changelog:
  exclude:
    labels:
      - norelease
      - release
  categories:
    - title: Breaking Changes 🔥
      labels:
        - breaking-change
    - title: Exciting New Features ✨
      labels:
        - feat
    - title: Bugfixes 🐛
      labels:
        - fix
    - title: Other Changes 🔄
      labels:
        - "*"
